export interface actionTypesInterficie {
LOAD_ALL_MOVIES: string,
LOAD_ALL_FAVOURITES: string,
ADD_FAVOURITES: string,
DELETE_FAVOURITES: string,
UPDATE_FAVOURITES: string,
FILTER_FAVOURITES: string,
}

const movieActionTypes: actionTypesInterficie = {
  LOAD_ALL_MOVIES: 'LOAD_ALL_MOVIES',
  LOAD_ALL_FAVOURITES: 'LOAD_ALL_FAVOURITES',
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  DELETE_FAVOURITES: 'DELETE_FAVOURITES',
  UPDATE_FAVOURITES: 'UPDATE_FAVOURITES',
  FILTER_FAVOURITES: 'FILTER_FAVOURITES'
}

export default movieActionTypes
