export default {
  LOAD_ALL_MOVIES: 'LOAD_ALL_MOVIES',
  LOAD_ALL_FAVOURITES: 'LOAD_ALL_FAVOURITES',
  ADD_FAVOURITES: 'ADD_FAVOURITES',
  DELETE_FAVOURITES: 'DELETE_FAVOURITES',
  UPDATE_FAVOURITES: 'UPDATE_FAVOURITES',
  FILTER_FAVOURITES: 'FILTER_FAVOURITES'
};
